Feature/personal info
mapadoacolhimento/cadastro-msr pull request #10
Opened 2024-07-09 20:17 UTC by gloriateodoro

- [x]  Adiciona campo Select com estilização e validação

- [x] altera TextInput para solucionar conflitos de estilização

- [ ] Add campo de data de nascimento

- [ ] Adiciona campo de Cor e PCD na mesma tela

2024-07-10 17:41 UTC, vivianedias requested changes

2024-07-10 17:41 UTC, vivianedias commented on src/components/MultiStepForm/Steps/__tests__/DiversityInformation.spec.tsx
> +		expect(screen.getAllByText("Esse campo é obrigatório."));
sem assertion

2024-07-10 17:41 UTC, vivianedias commented on src/components/MultiStepForm/Steps/__tests__/DiversityInformation.spec.tsx
> +	it("should display error if disability status is empty", async () => {
mesmo problema do teste anterior

2024-07-10 17:41 UTC, vivianedias commented on src/components/MultiStepForm/index.tsx
> +	disabilityStatus: string;
esses novos campos precisam bater com o nome das colunas que colocamos no prisma

2024-07-10 17:41 UTC, vivianedias commented on src/components/SelectInput/SelectInput.tsx
> +			<select
pq nao estamos usando o Select do radix?

2024-07-10 17:41 UTC, vivianedias commented on src/components/SelectInput/SelectInput.tsx
> +				aria-invalid={hasError ? "true" : "false"}
quais sao as propriedades de acessibilidade que precisamos pro select? esse `aria-invalid` faz sentido pro select? tem q checar o MDN

2024-07-10 17:41 UTC, vivianedias commented on cypress/e2e/App.cy.ts
> +	it("should display error if date of birth field is empty", () => {
podemos separar os testes que sao de componente em arquivos separadas e os testes do fluxo completo deixamos aq, pls?

2024-07-10 17:41 UTC, vivianedias commented on cypress/e2e/App.cy.ts
> +	it("should display error if date of birth field is empty", () => {
tb podemos criar comandos customizados colocando esses `type` 

por ex: 

```
fillFirstStep() {
		cy.get("#name").type("MSR teste");
		cy.get("#email").type("msr@test.com");
		cy.get("#confirmEmail").type("msr@test.com");
		cy.get("#phone").type("9999");
}
```

algo assim, a doc esta aq: https://docs.cypress.io/api/cypress-api/custom-commands

2024-07-10 17:41 UTC, vivianedias commented on src/components/TextInput/TextInput.tsx
>  	}
passar onBlur do field do formik

2024-07-10 17:41 UTC, vivianedias commented on src/components/index.ts
> -export { default as TextInput } from "./TextInput";
podemos manter o padrao de o arquivo ser `index.tsx`?

2024-07-10 17:41 UTC, vivianedias commented on src/components/TextInput/TextInput.css
> +	border-radius: 6px;
o proprio radix tem uma propriedade de `border-radius` vamos seguir o padrao deles

2024-07-10 17:41 UTC, vivianedias commented on src/components/SelectInput/SelectInput.tsx
> +			{hasError && <div className="input-feedback">{meta.error}</div>}
vamos usar o componente `ErrorMessage` que já padroniza essa parte de erros

2024-07-10 17:48 UTC, vivianedias commented on src/components/SelectInput/SelectInput.tsx
> +				aria-invalid={hasError ? "true" : "false"}
o Select não é selecionavel via `tab`

2024-07-10 17:59 UTC, vivianedias requested changes

2024-07-10 17:59 UTC, vivianedias commented on src/components/MultiStepForm/index.tsx
>  			{SupportType()}
esses dois passos estao estranhos, diferente de PROD

2024-07-11 13:16 UTC, gloriateodoro commented on src/components/index.ts
> -export { default as TextInput } from "./TextInput";
não tá rolando com o TextInput, podemos ver juntas

2024-07-12 13:59 UTC, vivianedias requested changes
nao consigo sair do primeiro passo, é um erro com o endpoint /validate. precisa dar um pull da main para tentar resolver, pois é algo relacionado a coluna `last_name`

2024-07-12 13:59 UTC, vivianedias commented on cypress/e2e/App.cy.ts
> +	});
nao estamos checando se chegamos no passo 3

2024-07-12 13:59 UTC, vivianedias commented on cypress/e2e/App.cy.ts
> +		cy.fillSecondStep();
poderia ser so uma busca pelo titulo do step dois inves de preencher todo o passo

2024-07-12 13:59 UTC, vivianedias commented on src/components/CheckboxInput/CheckboxInput.css
> +}
nao precisamos remover isso, acho q o checkbox é uma coisa boa nesse componente. tinha mencionado isso em uma das nossas reunioes

2024-07-12 13:59 UTC, vivianedias commented on src/components/MultiStepForm/Steps/BasicRegisterInformation.tsx
> +				type="name"
nao existe type name

2024-07-12 13:59 UTC, vivianedias commented on src/components/MultiStepForm/Steps/__tests__/DiversityInformation.spec.tsx
> +		expect(screen.getAllByText("Esse campo é obrigatório."));
nao foi corrigido

2024-07-12 13:59 UTC, vivianedias commented on src/components/MultiStepForm/Steps/__tests__/DiversityInformation.spec.tsx
> +		const colorInput = screen.getByLabelText("Cor");
nao foi corrigido

2024-07-12 13:59 UTC, vivianedias commented on src/components/SelectInput/index.tsx
> +			<select
ainda nao estamos usando o select do radix

2024-07-12 16:25 UTC, gloriateodoro commented on src/components/SelectInput/SelectInput.css
> +label {
estranho, não existe mais esse label, ele já tá atualizado, mas pra você apareceu a versão antiga. Consegue visualizar novamente? olhei aqui e já tá atualizado na minha branch

2024-07-12 16:29 UTC, gloriateodoro commented on src/components/CheckboxInput/CheckboxInput.css
> +}
ah, eu segui o comportamento do figma, mas vou retornar

2024-07-12 16:35 UTC, gloriateodoro commented on cypress/e2e/App.cy.ts
> +		cy.fillSecondStep();
o título da step é igual na primeira e segunda etapa, então se permanecesse na etapa 1 o teste passaria

2024-07-12 17:39 UTC, vivianedias approved these changes

2024-07-12 17:43 UTC, vivianedias commented
Por conta do force-push eu vou ter que mergear com bypass das proteções da branch, pois não consigo resolver comentários em outras revisões que foram feitas anteriormente

2024-07-12 17:43 UTC, merged