[MAPA-464] add endpoint create
mapadoacolhimento/cadastro-msr pull request #11
Opened 2024-07-10 17:25 UTC by dieh

2024-07-10 20:37 UTC, vivianedias requested changes

2024-07-10 20:37 UTC, vivianedias commented on package.json
> +		"vitest-mock-extended": "^1.3.1",
isso é uma devDependency

2024-07-10 20:37 UTC, vivianedias commented on src/app/__mocks__/db.ts
> +import { vi } from "vitest";
migrar isso para dentro do `src/lib`, o `app` é só para paginas públicas

2024-07-10 20:37 UTC, vivianedias commented on src/app/__mocks__/db.ts
> +export const mockedDb = db as unknown as DeepMockProxy<PrismaClient>;
```suggestion
const mockedDb = db as unknown as DeepMockProxy<PrismaClient>;
export default mockedDb
```

2024-07-10 20:37 UTC, vivianedias commented on src/app/__tests__/create.spec.ts
> +import { expect } from "vitest";
nao precisa importar o expect, ele vem como um global

2024-07-10 20:37 UTC, vivianedias commented on src/app/__tests__/create.spec.ts
> +import { Gender, MSRStatus, Prisma, Race } from "@prisma/client";
```suggestion
import { type Gender, type MSRStatus, Prisma, type Race } from "@prisma/client";
```

2024-07-10 20:37 UTC, vivianedias commented on src/app/__tests__/create.spec.ts
> +	it("shoul create new msr with basics fields on db", async () => {
```suggestion
	it("should create new msr with basics fields on db", async () => {
```

2024-07-10 20:37 UTC, vivianedias commented on src/app/__tests__/create.spec.ts
> +	it("shoul create new msr with basics fields on db", async () => {
pq temos "basic" e "all" fields?

2024-07-10 20:37 UTC, vivianedias commented on src/app/create/route.ts
> +	accepts_online_support: Yup.boolean(),
nao usar snake case, apenas camelCase seguindo padrao do JS e do proprio prisma

2024-07-10 20:37 UTC, vivianedias commented on src/app/create/route.ts
> +				gender: payload.gender ? payload.gender : "not_found",
```suggestion
				gender: payload.gender
```

isso deve ser tratado la no `listener-solidarity` quando chamarmos o endpoint, nao precisa tratar aq

2024-07-10 20:37 UTC, vivianedias commented on src/app/create/route.ts
> +					: true,
aq tb

2024-07-10 20:37 UTC, vivianedias commented on src/app/create/route.ts
> +				zipcode: payload.zipcodez ? payload.zipcodez : "not_found",
```suggestion
				zipcode: payload.zipcode ? payload.zipcode : "not_found",
```

2024-07-10 20:37 UTC, vivianedias commented on src/app/create/route.ts
> +	zendesk_user_id: Yup.number().required(),
```suggestion
	msrZendeskUserId: Yup.number().required(),
```

2024-07-10 20:37 UTC, vivianedias commented on src/app/create/route.ts
> +					: null,
```suggestion
				dateOfBirth: new Date(payload.date_of_birth).toISOString()
```

2024-07-10 20:37 UTC, vivianedias commented on src/app/create/route.ts
> +			msr_id: msr.msrId.toString(),
acho q so responder o ID ta sucesso

2024-07-10 20:37 UTC, vivianedias commented on src/app/create/route.ts
> +	state: Yup.string().required(),
```suggestion
	state: Yup.string().required().max(2),
```

add q o state tem q so ter duas letras

2024-07-10 20:37 UTC, vivianedias commented on src/app/create/route.ts
> +	zipcode: Yup.string(),
add validação de tamanho do zipcode

2024-07-10 20:37 UTC, vivianedias commented on src/app/create/route.ts
> +	date_of_birth: Yup.date().nullable(),
nao pode ser nullable

2024-07-10 20:37 UTC, vivianedias commented on src/app/create/route.ts
> +	had_disability: Yup.boolean(),
required

2024-07-10 20:37 UTC, vivianedias commented on src/app/create/route.ts
> +	accepts_online_support: Yup.boolean(),
required

2024-07-10 20:37 UTC, vivianedias commented on src/app/create/route.ts
> +	zipcode: Yup.string(),
required

2024-07-10 20:37 UTC, vivianedias commented on src/app/create/route.ts
> +	last_name: Yup.string(),
required

2024-07-10 20:37 UTC, vivianedias commented on src/app/create/route.ts
> +	gender: Yup.string().oneOf(Object.values(Gender)),
required

2024-07-10 20:37 UTC, vivianedias commented on src/app/create/route.ts
> +	accepts_online_support: Yup.boolean(),
required

2024-07-10 20:37 UTC, vivianedias commented on src/app/create/route.ts
> +});
add q o objeto é required e retirar a validação de empty body, isso ja era pra conseguir checar o body

2024-07-10 20:37 UTC, vivianedias commented on src/types/index.ts
> +export type Msr = Pick<
pq fizemos o pick? a q e ali embaixo

2024-07-11 12:10 UTC, dieh commented on src/app/create/route.ts
> +	last_name: Yup.string(),
o last_name?

2024-07-11 12:16 UTC, dieh commented on src/app/__tests__/create.spec.ts
> +import { expect } from "vitest";
Pediu pelo import na verdade, mas vou olhar o que pode ter acontecido

2024-07-11 18:56 UTC, dieh commented on src/types/index.ts
> +export type Msr = Pick<
Era uma questão que tava com o retorno mas acabei resolvendo de outra forma e acabei num tirando depois

2024-07-11 19:12 UTC, dieh commented on src/app/__tests__/create.spec.ts
> +import { expect } from "vitest";
Ainda não consegui resolver essa questão

2024-07-15 19:49 UTC, vivianedias approved these changes

2024-07-15 20:20 UTC, merged