[MAPA-420] - add search endpoint
mapadoacolhimento/cadastro-msr pull request #16
Opened 2024-07-23 14:38 UTC by dieh

2024-07-25 18:03 UTC, vivianedias requested changes
ficou perfeito :) so alguns pontinhos de console.log e typo! 💅🏾

2024-07-25 18:03 UTC, vivianedias commented on src/app/__tests__/search.spec.ts
> +	it("returns false when msr, two support request exits", async () => {
```suggestion
	it("should return `continue: false` when msr exists and has two support requests", async () => {
```

2024-07-25 18:03 UTC, vivianedias commented on src/app/__tests__/search.spec.ts
> +	it("returns true when msr does not exits", async () => {
```suggestion
	it("should return `continue: true` when msr does not exist", async () => {
```

2024-07-25 18:03 UTC, vivianedias commented on src/app/__tests__/search.spec.ts
> +	it("returns error when dont have a valid payload", async () => {
```suggestion
	it("should return an error when theres not a valid payload", async () => {
```

2024-07-25 18:03 UTC, vivianedias commented on src/app/__tests__/search.spec.ts
acho q so faltou o caso quando tem msr mas nao tem support_request!

2024-07-25 21:14 UTC, camilacrdoso reviewed
mulheres, essas regras de solicitação repetida são complexas né? 😢 

fiquei com algumas dúvidas existenciais e deixei nos comentários

2024-07-25 21:14 UTC, camilacrdoso commented on src/app/search/route.ts
> +				status: { in: statusSuppotRequestInProgress },
gente, tava pensando aqui e acho que vamos ter que olhar pro match mesmo 😭  

porque o `support_request` pode estar `matched` mas o match pode estar `interrupted_before_support` ou `interrupted_after_support` 

então talvez a lógica podia checar 3 condições tipo:
`hasOnGoingMatch || hasOnGoingSocialWorker || isAlreadyInQueue`

- `hasOnGoingMatch`: se tem algum match com status `waiting_contact` ou `in_contact`
- `hasOnGoingSocialWorker`: se tem support_request com status `social_worker` ou `scheduled_social_worker`
- `isAlreadyInQueue`: se tem support_request com status `waiting_for_match` ou `waiting_for_match_with_priority` 

o que acham?

2024-07-25 21:14 UTC, camilacrdoso commented on src/app/search/route.ts
> +				supportType: { in: payload.supportTypes },
gente, outra coisa que fiquei pensando aqui:

se a mulher já tiver um pedido de acolhimento antigo **psicológico** e pedir acolhimento **jurídico e psicológico**, isso vai bloquear ela de receber o match jurídico né?

não sei exatamente como lidar com isso hahahah mas talvez valha a gente discutir

2024-07-25 21:14 UTC, camilacrdoso commented on src/app/search/route.ts
> +			status: "open",
será que deveríamos tbm mudar o status do acolhimento pra solicitação repetida e o support_request pra `duplicated` e aí as meninas de provisão criam uma visualização no Zendesk pra elas acompanharem esses casos?

2024-07-25 21:14 UTC, camilacrdoso commented on src/app/search/route.ts
> +				continue: true,
nesse caso, vamos chamar o endpoint da lambda do novo match que cria o support_request, criar o ticket no Zendesk, etc né? mas pode ser que já exista support_request (tipo `status = public_service`) 

então talvez, além do `continue`, aqui a gente precise retornar algo tipo `shouldCreateNewSupportRequest`?

2024-07-26 19:47 UTC, dieh commented on src/app/search/route.ts
> +				status: { in: statusSuppotRequestInProgress },
Só pra ver se eu entendi, seria para ver se existe um match em aberto e depois ver qual o status do support_request?

2024-07-26 19:49 UTC, dieh commented on src/app/search/route.ts
> +				supportType: { in: payload.supportTypes },
Sim! A opção seria orientá-la? Ou continuar o pedido que ela não teria ainda?

2024-07-26 19:52 UTC, dieh commented on src/app/search/route.ts
> +				continue: true,
No caso seria pq iremos atualizar o dados dela? Mesmo sendo repetido?

2024-07-29 14:40 UTC, vivianedias commented on src/lib/zendesk/updateManyTickets.ts
> +};
querida, nao entendi pq precisamos desse type, nao passamos os ids na url?

qual seria o caso em q esse type faria sentido?

2024-07-29 15:37 UTC, dieh commented on src/lib/zendesk/updateManyTickets.ts
> +};
Então, esse tipo é para os casos que de quando precisamos  atualizar[ mais de um ticket mas com atualizações diferentes](https://developer.zendesk.com/api-reference/ticketing/tickets/tickets/#update-many-tickets). Não é o caso no search mesmo mas achei que deveria deixar essa opção se formos reutilizar essa função em outro momento. Mas se achar melhor eu posso remover pq não afeta a chamada atual.

2024-07-30 21:44 UTC, camilacrdoso approved these changes

2024-07-30 21:44 UTC, camilacrdoso commented on src/lib/constants.ts
> +	MatchStatus.started_contact,
```suggestion
```

2024-07-31 11:09 UTC, vivianedias approved these changes

2024-07-31 11:09 UTC, camilacrdoso approved these changes

2024-07-31 11:09 UTC, merged