[MAPA-491] feat: add home screen
mapadoacolhimento/cadastro-msr pull request #20
Opened 2024-07-30 13:24 UTC by gloriateodoro

2024-07-31 18:14 UTC, vivianedias commented
#### 📝 Changed routes:


| [**/cadastro**](https://msr-register-form-5kwa5wesk-desenvolvimento-mapa.vercel.app/cadastro) | [**/**](https://msr-register-form-5kwa5wesk-desenvolvimento-mapa.vercel.app/) |
|:-:|:-:|
|<a href="https://msr-register-form-5kwa5wesk-desenvolvimento-mapa.vercel.app/cadastro"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/iGii-TpMcs9viXFMVQ1UhSYscz_DilrR6oQAkuzRNNE9V7ACQyc4o8GYSxC0H82zsRXaRsuncgKntPqoxNmFXw.png&w=600" alt="Screenshot of /cadastro" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/TqO-YB1C0oDHVOvKSpyN6mnu3IK38NsRQTvM2GhD9Am3yRFcvJCvKmJuoYOYavW32I6HO8GkhNr47enQeBdAtA.png">(view full size)</a> |<a href="https://msr-register-form-5kwa5wesk-desenvolvimento-mapa.vercel.app/"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/TPO3oU5SbkJWBGic9WJC473-NBURd6sftdCg79DvyxOkSQI4m2IbxKxkvShwgSS9PPzwtcMkgmMmkVsqhv7iPQ.png&w=600" alt="Screenshot of /" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/IRFiHRxmvtfwj1AuFg-w4ia3oAGbHUBRo8UNRVZ8_r_WGuqAMycv7B4-2_Hj0y2sbX2P8hgll-ogpZ1eX0RSBg.png">(view full size)</a> |







Commit ab214988bb9cb68a2f9e612b1aafb0285d7597a0 (https://msr-register-form-5kwa5wesk-desenvolvimento-mapa.vercel.app).

2024-07-31 18:57 UTC, gloriateodoro reviewed
Aqui eu precisei tirar o componente DesktopIllustration porque nesse caso, como não há barra de progresso, queremos que a ilustração fique fixada na parte inferior da tela, diferentemente das outras telas. Apenas por esse motivo não vamos reaproveitar o componente

2024-08-01 13:19 UTC, vivianedias requested changes
show <3

2024-08-01 13:19 UTC, vivianedias commented on public/illustrations/three_women.svg
eu tinha add esse .svg no outro PR com o nome `women-support.svg`!

2024-08-01 13:19 UTC, vivianedias commented on cypress/e2e/components.cy.ts
> +it.only("should display error if disability status field is empty", () => {
tb tem um issue do SonarCloud!

2024-08-01 15:10 UTC, gloriateodoro commented on cypress/e2e/components.cy.ts
> +it.only("should display error if disability status field is empty", () => {
@vivianedias eu removi o teste de cor porque agora ele tá em outra página, esse teste tava desatualizado

2024-08-01 15:42 UTC, vivianedias approved these changes

2024-08-01 17:40 UTC, merged