[MAPA-425] feat: add feedback screens
mapadoacolhimento/cadastro-msr pull request #24
Opened 2024-08-06 12:57 UTC by gloriateodoro

- [x] Adiciona tela de sucesso temporária: Agora é só esperar 

- [x] Adiciona tela de carregamento com testes

- [x] Adiciona tela de falha
- [x] Adiciona testes

2024-08-06 13:41 UTC, vivianedias commented
#### 📝 Changed routes:


| [**/wait**](https://msr-register-form-6g4taja79-desenvolvimento-mapa.vercel.app/wait) |
|:-:|
|<a href="https://msr-register-form-6g4taja79-desenvolvimento-mapa.vercel.app/wait"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/uFPbjF0Ohrz2zLhienyx3VRC7l5WJnx5c4-uhkWGw6vp0KqhjyGlms22AxkDHWXhHtjtdMjyrWV6uUaRS3-shw.png&w=600" alt="Screenshot of /wait" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/tRTWHTE6ulGJ4hGsdjR5zdO1RvPqah8O0OPTzODCbUaV9KIcvO7wVAbeTymI651A-_hakPhdTf6H4Y_-y7DXig.png">(view full size)</a> |







Commit afc27b93a9f87759e41327b3f7afacde8a17e8f6 (https://msr-register-form-6g4taja79-desenvolvimento-mapa.vercel.app).

2024-08-08 20:08 UTC, dieh commented on src/components/MultiStepForm/MultiStepFormWrapper.tsx
> +								{isLoading ? <LoadingStep /> : null}
Checar o isLoading aqui não vai carregar a pagina de loading a cada passo? Ou é só correspondente ao passo final?

2024-08-12 13:53 UTC, gloriateodoro commented on src/components/MultiStepForm/MultiStepFormWrapper.tsx
> +								{isLoading ? <LoadingStep /> : null}
boa, muito obrigada! realmente tá em todos os passos dessa forma, acabei de consertar

2024-08-12 17:27 UTC, vivianedias requested changes

2024-08-13 17:26 UTC, merged