feat: add redirection to fora-criterios page when msr is under 18
mapadoacolhimento/cadastro-msr pull request #28
Opened 2024-08-12 18:34 UTC by gloriateodoro

- [ ] Faz cálculo de idade e direciona para página de fora-critérios quando a MSR for menor de idade
- [ ] Adiciona testes

2024-08-12 20:33 UTC, dieh commented on src/components/MultiStepForm/Steps/BasicRegisterInformation.tsx
> +	const birthDate = new Date(year, month - 1, day);
Por quê tá diminuindo o mês para gerar o Date? Algum detalhe específico pra essa conversão?

2024-08-13 14:45 UTC, vivianedias requested changes

2024-08-13 14:45 UTC, vivianedias commented on src/components/MultiStepForm/Steps/BasicRegisterInformation.tsx
> +	const birthDate = new Date(year, month - 1, day);
perguntei para o chatgpt e ele disse q "o mês em JavaScript começam em 0, por isso é subtraído 1"

2024-08-13 14:45 UTC, vivianedias commented on src/components/MultiStepForm/Steps/BasicRegisterInformation.tsx
> +};
minha recomendaçao pra funçao pra melhorar as variaveis:

```
const isAdult = (dateOfBirth: string) => {
	const [day, month, year] = dateOfBirth.split("/").map(Number);
	const birthDate = new Date(year, month - 1, day);
	let ageDifference = today.getFullYear() - birthDate.getFullYear();
	const monthDifference = today.getMonth() - birthDate.getMonth();

	const hasNotReachedBirthdayMonth = monthDifference < 0;
	const isBirthdayMonth = monthDifference === 0;
	const hasNotPassedBirthdayThisYear =
		hasNotReachedBirthdayMonth ||
		(isBirthdayMonth && today.getDate() >= birthDate.getDate());

	if (hasNotPassedBirthdayThisYear) {
		ageDifference--;
	}

	return ageDifference >= 18;
};
```

nesse caso a função checa se a pessoa é adulta. tb sugiro colocar ela no `/lib` e criar testes

2024-08-13 14:47 UTC, vivianedias commented on cypress/e2e/App.cy.ts
> +		cy.get("#dateOfBirth").type("18112015");
tem que add o ano em uma variavel, pq 2015 pode ser maior de idade logo menos rs

2024-08-13 17:28 UTC, gloriateodoro commented on src/components/MultiStepForm/Steps/BasicRegisterInformation.tsx
> +	const birthDate = new Date(year, month - 1, day);
exatamente

2024-08-14 17:11 UTC, vivianedias commented on src/lib/index.ts
> +export { isDateValid } from "./isDateValid";
```suggestion
export { default as isAdult } from "./isAdult";
export { default as isDateValid } from "./isDateValid";
```

2024-08-14 20:32 UTC, vivianedias approved these changes

2024-08-14 20:32 UTC, merged