[MAPA-462] add load-msr-register-data
mapadoacolhimento/cadastro-msr pull request #51
Opened 2024-10-10 18:50 UTC by dieh

2024-10-23 18:02 UTC, vivianedias requested changes

2024-10-23 18:02 UTC, vivianedias commented on src/app/db/load-msr-register-data/route.ts
> +		await paramSchema.validate(email);
```suggestion
		const validatedEmail = await paramSchema.validate(email);
```

2024-10-23 18:49 UTC, dieh commented on src/utils/__tests__/updateEmptyFields.spec.ts
> +});
só não coloquei o ultimo pq não estamos lidando com objetos aninhados no momento.

2024-10-24 14:32 UTC, vivianedias commented on src/utils/gerarEmail.ts
> +export default function gerarEmail() {
```suggestion
export default function generateTestEmail() {
```

2024-10-24 14:34 UTC, vivianedias commented on src/components/MultiStepForm/Steps/BasicRegisterInformation.tsx
> +			if (response.ok) {
ele não throw automaticamente, entao a gente tem q jogar o erro aq 

```
		if (!response.ok) {
			throw new Error(response.statusText);
		}
```

2024-10-24 14:37 UTC, vivianedias commented on src/components/MultiStepForm/Steps/BasicRegisterInformation.tsx
> +			logger.error(error);
```suggestion
			logger.error(error.message);
			window.newrelic.noticeError(
				Error("Error fetching msr '${email}' register data")
			);
```

2024-10-24 18:35 UTC, vivianedias approved these changes

2024-10-28 14:48 UTC, vivianedias approved these changes

2024-10-28 14:50 UTC, merged