[MAPA-415] Feature/fields
mapadoacolhimento/cadastro-msr pull request #7
Opened 2024-07-03 13:52 UTC by gloriateodoro

- [ ] adiciona componente padrão TextInput

- [ ] isola barra de progresso para permitir estilização do formulário

- [ ] adiciona react-input-mask para criação de máscaras

- [ ] adiciona campos de nome, e-mail, confirmação de e-mail e whatsapp

2024-07-03 21:35 UTC, vivianedias requested changes

2024-07-03 21:35 UTC, vivianedias commented on src/components/MultiStepForm/MultiStepFormWrapper.tsx
>  						)}
pode deixar o Form onde ele estava, incluindo o IconButton

2024-07-03 21:35 UTC, vivianedias commented on src/components/MultiStepForm/Steps/BasicRegisterInformation.tsx
> +				type="name"
```suggestion
```

nao existe esse type, pode deixar sem pq default é text

2024-07-03 21:35 UTC, vivianedias commented on src/components/TextInput/TextInput.css
> +	font-size: 16px;
usar variavel de font-size do radix

2024-07-03 21:35 UTC, vivianedias commented on src/components/TextInput/TextInput.css
> +	border: 1px solid #ccc;
usar variavel de cor de borda do radix

2024-07-04 13:37 UTC, gloriateodoro commented on src/components/MultiStepForm/MultiStepFormWrapper.tsx
>  						)}
fiz a modificação alterando a identação do meu vscode pra 2 tabs em vez de 4, salvei o arquivo, mas essa modificação não aparece no versionamento, acredito que tem que modificar alguma linha

2024-07-04 14:54 UTC, vivianedias requested changes
amei os testes 💅🏾 ta arrasando!

2024-07-04 14:54 UTC, vivianedias commented on src/components/MultiStepForm/Steps/BasicRegisterInformation.tsx
> +				type="whatsapp"
pode manter phone, pq no banco a coluna vai ter esse nome

2024-07-04 14:54 UTC, vivianedias commented on src/components/MultiStepForm/Steps/__tests__/BasicRegisterInformation.spec.tsx
> +		expect(alerts[0]).toHaveTextContent("Esse campo é obrigatório.");
se vai ter só um alert na na tela, entao nao precisa usar o findByAll, eai a linha 72 pode sair

pode ser tipo

```
expect(await screen.findByRole('alert')).toBeInTheDocument()
expect(screen.getByRole('alert')).toHaveTextContent("Esse campo é obrigatório.")
```

2024-07-04 14:54 UTC, vivianedias commented on src/components/MultiStepForm/Steps/__tests__/BasicRegisterInformation.spec.tsx
> +		const alerts: HTMLElement[] = await screen.findAllByRole("alert");
```suggestion
		const alerts: HTMLElement[] = await screen.findAllByRole("alert");
		expect(alerts).toHaveLength(2);
```

2024-07-04 14:54 UTC, vivianedias commented on src/components/MultiStepForm/Steps/__tests__/BasicRegisterInformation.spec.tsx
> +		const alerts: HTMLElement[] = await screen.findAllByRole("alert");
msm coisa aq, se sabemos que tem so um alerta, nao usar findByAll

2024-07-04 14:54 UTC, vivianedias commented on src/components/MultiStepForm/Steps/__tests__/BasicRegisterInformation.spec.tsx
> +		expect(alerts[3]).toHaveTextContent(
vamos manter o padrao q vc fez nos outros testes de preencher os outros campos corretamente, eai aq busca findByRole, inves de findAllByRole

2024-07-04 17:11 UTC, vivianedias requested changes
so um pequeno ajuste aqui, testes lindooooossssss <3

2024-07-04 17:11 UTC, vivianedias commented on cypress/e2e/App.cy.ts
> +		cy.get("#whatsapp").type("(81) 99999-9999");
```suggestion
		cy.get("#whatsapp").type("81999999999");
```

2024-07-04 17:53 UTC, vivianedias commented on src/components/MultiStepForm/MultiStepFormWrapper.tsx
> +							<>
faltou colocar o Form em volta de tudo

2024-07-04 17:57 UTC, vivianedias approved these changes
uhuuuul

2024-07-04 17:58 UTC, merged